//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _MICROSOFT_SPOT_MFCONFIGHELPER_H_
#define _MICROSOFT_SPOT_MFCONFIGHELPER_H_

#include <TinyCLR_Interop.h>
struct Library_Microsoft_SPOT_MFConfigHelper_Microsoft_SPOT_MFConfigHelper
{
    static const int FIELD__m_isDisposed = 1;

    TINYCLR_NATIVE_DECLARE(WriteConfigBlock___STATIC__BOOLEAN__STRING__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(ReadConfigBlock___STATIC__BOOLEAN__STRING__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(InvalidateBlockWithName___STATIC__BOOLEAN__STRING);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_MFConfigHelper;

#endif  //_MICROSOFT_SPOT_MFCONFIGHELPER_H_
