//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Microsoft_SPOT_MFConfigHelper.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Microsoft_SPOT_MFConfigHelper_Microsoft_SPOT_MFConfigHelper::WriteConfigBlock___STATIC__BOOLEAN__STRING__SZARRAY_U1,
    Library_Microsoft_SPOT_MFConfigHelper_Microsoft_SPOT_MFConfigHelper::ReadConfigBlock___STATIC__BOOLEAN__STRING__SZARRAY_U1,
    Library_Microsoft_SPOT_MFConfigHelper_Microsoft_SPOT_MFConfigHelper::InvalidateBlockWithName___STATIC__BOOLEAN__STRING,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_MFConfigHelper =
{
    "Microsoft.SPOT.MFConfigHelper", 
    0xBEF07CD9,
    method_lookup
};

